config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  root 'static_pages#top'

  get 'about' => 'static_pages#about'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def append_info_to_payload(payload)
    super
    payload[:remote_ip] = request.env['HTTP_X_FORWARDED_FOR'] || request.remote_ip
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(level)
    case level
    when 'success' then 'alert-success'
    when 'notice'  then 'alert-info'
    when 'alert'   then 'alert-warning'
    when 'error'   then 'alert-danger'
    end
  end
end

app/views/layouts/_footer.html.slim
footer
  .container
    br
    hr

    p &copy; 2014-2015 Ikuo Terado

app/views/layouts/_header.html.slim
header.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "rails-base", root_path, class: "navbar-brand", id: "logo"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1

      ul.nav.navbar-nav
        li
          = link_to "About", about_path

      ul.nav.navbar-nav.navbar-right
        li
          .dropdown
            button.btn.btn-default.dropdown-toggle#dropdownMenuAction type="button" data-toggle="dropdown"
              | Action
              span.caret<
            ul.dropdown-menu role="menu" aria-labelledby="dropdownMenuAction"
              li role="presentation"
                = link_to "Action"
        li
          div
            - if !user_signed_in?
              = link_to "Sign in", sign_in_path, class: "btn btn-success"
            - else
              .dropdown
                button.btn.btn-default.dropdown-toggle#dropdownMenuUser type="button" data-toggle="dropdown"
                  = current_user.name
                  span.caret<
                ul.dropdown-menu role="menu" aria-labelledby="dropdownMenuUser"
                  li role="presentation"
                    = link_to "Sign out", sign_out_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title RailsBase
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render partial: 'layouts/header'

    .container
      - flash.each do |key, value|
        .alert.alert-dismissible class="#{bootstrap_class_for(key)}"
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = value

    .container
      = yield

    = render partial: 'layouts/footer'

app/views/static_pages/about.html.slim
h1 StaticPages#about
p Find me in app/views/static_pages/about.html.slim

app/views/static_pages/top.html.slim
.jumbotron
  h1 Hello, world!
  p This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
  p
    = link_to "Learn more »", about_path, class: "btn btn-primary btn-lg"

.row
  .col-md-4
    h3 Heading
    p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
  .col-md-4
    h3 Heading
    p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
  .col-md-4
    h3 Heading
    p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.